<?php
// whatsapp_report.php - Integrated WhatsApp Report Engine using 2fa.tehub.in API
header('Content-Type: application/json');
require_once __DIR__ . '/db.php';

// Parse raw input
$rawInput = @file_get_contents('php://input');
$jsonData = !empty($rawInput) ? json_decode($rawInput, true) : [];
$requestData = array_merge($_REQUEST, $jsonData);

// Pre-configured WhatsApp API Settings from tehub.in
$DEFAULT_API_URL = "https://2fa.tehub.in/api/whatsapp.php";
$DEFAULT_API_KEY = "2afb55e8bbc3d8d6ca018fd19592a4ee";

$apiUrl = trim($requestData['api_url'] ?? '') ?: $DEFAULT_API_URL;
$apiKey = trim($requestData['api_key'] ?? '') ?: $DEFAULT_API_KEY;
$phone = trim($requestData['phone'] ?? '');

try {
    // Fetch live metrics
    $totalClients = (int)$pdo->query("SELECT COUNT(*) FROM clients")->fetchColumn();
    
    $countsStmt = $pdo->query("SELECT status, COUNT(*) as count FROM clients GROUP BY status");
    $rawCounts = $countsStmt->fetchAll(PDO::FETCH_KEY_PAIR);

    $stageCounts = [];
    foreach ($STAGES as $stage) {
        $stageCounts[$stage] = (int)($rawCounts[$stage] ?? 0);
    }

    $docsPending = $stageCounts['Documents Pending'];
    $docsCollected = $stageCounts['Documents Collected'];
    $bankTransferred = $stageCounts['Bank Transferred (Waiting for Login)'];
    $loginDocs = $stageCounts['Login with Documents'];
    $sanctionWait = $stageCounts['Waiting for Sanction'];
    $sanctioned = $stageCounts['Sanction'];
    $completed = $stageCounts['Completed'];
    $onHold = $stageCounts['On Hold'];
    $nextMonth = $stageCounts['Next Month Lead'];

    $dateStr = date('d M Y, h:i A');

    // Format WhatsApp Markdown Report Message
    $msg  = "📊 *CREDFIX.IN - DAILY CLIENT STATUS REPORT*\n";
    $msg .= "📅 *Date:* {$dateStr}\n\n";
    
    $msg .= "📈 *EXECUTIVE SUMMARY:*\n";
    $msg .= "• *Total Clients:* {$totalClients}\n";
    $msg .= "• 📋 *Documents Pending:* {$docsPending}\n";
    $msg .= "• 📂 *Documents Collected:* {$docsCollected}\n";
    $msg .= "• 🏦 *Bank Transferred:* {$bankTransferred}\n";
    $msg .= "• 🔐 *Login Done:* {$loginDocs}\n";
    $msg .= "• ⏳ *Waiting for Sanction:* {$sanctionWait}\n";
    $msg .= "• 🎉 *Completed Cases:* {$completed}\n";
    $msg .= "• ⏸️ *On Hold Cases:* {$onHold}\n\n";

    $msg .= "📍 *DETAILED 8-STAGE BREAKDOWN:*\n";
    foreach ($STAGES as $idx => $stage) {
        $count = $stageCounts[$stage];
        $stageNum = $idx + 1;
        $msg .= "{$stageNum}. {$stage}: *{$count}*\n";
    }

    $msg .= "\n🔗 *Portal:* https://credifix.in/status/\n";
    $msg .= "📲 _Generated by Credfix Automated Engine_";

    // If no phone number provided, return report preview
    if (empty($phone)) {
        echo json_encode([
            'success' => true,
            'message' => 'Report generated (Enter recipient phone number to send)',
            'report_text' => $msg,
            'api_url' => $apiUrl,
            'api_key' => $apiKey,
            'metrics' => [
                'total' => $totalClients,
                'pending_docs' => $pendingDocs,
                'bank_processing' => $bankProc,
                'sanctioned' => $sanctioned,
                'completed' => $completed
            ]
        ]);
        exit;
    }

    // Clean phone number format (ensure no + or spaces)
    $cleanPhone = preg_replace('/[^0-9]/', '', $phone);

    // Send HTTP POST to https://2fa.tehub.in/api/whatsapp.php
    $ch = curl_init($apiUrl);
    
    $payload = [
        'to' => $cleanPhone,
        'message' => $msg,
        'type' => 'report'
    ];

    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => json_encode($payload),
        CURLOPT_HTTPHEADER => [
            'Content-Type: application/json',
            'Authorization: Bearer ' . $apiKey
        ],
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_TIMEOUT => 20
    ]);

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $curlError = curl_error($ch);
    curl_close($ch);

    $resData = json_decode($response, true);

    echo json_encode([
        'success' => $httpCode >= 200 && $httpCode < 300,
        'message' => 'WhatsApp Report Dispatched!',
        'http_code' => $httpCode,
        'api_response' => $resData ?: $response ?: $curlError,
        'report_text' => $msg
    ]);

} catch (Exception $e) {
    http_response_code(500);
    echo json_encode(['success' => false, 'error' => $e->getMessage()]);
}
